### ISSUE TITLE
smarter delete (like yEd)

### ISSUE THREAD

**Issue by adamfk** [StateSmith/StateSmith-drawio-plugin#2]
This shouldn't be too hard, but will take some time. Please ping me if you'd like to work on it.

yEd has a more useful delete feature than draw.io, but we should be able to reproduce the same behavior.

- [ ] if group is expanded and deleted, only remove the group and not its children
- [ ] if a group is collapsed and deleted, delete the group and anything nested inside it
- [ ] make sure that undo functionality still works

desired yEd behavior:
![good-delete](https://user-images.githubusercontent.com/274012/211231133-2d2aed65-ee68-4b00-af7c-8010954e0b10.gif)

current bad draw.io behavior:
![bad-delete](https://user-images.githubusercontent.com/274012/211231148-896ccb57-0742-4c95-8bdd-b4506da3bf45.gif)

**Comment by adamfk** [comment]
I'm currently using javascript: https://github.com/StateSmith/StateSmith-drawio-plugin/blob/main/StateSmith-drawio-plugin.js

At some point I'd like to switch to typescript if it will help make development easier.

I'll be recording a video in a day or so to help explain how to get started hacking on the plugin. Are you interested in helping work on this issue?

**Comment by 1san1** [comment]
yes i want to work on this issue

**Comment by adamfk** [comment]
awesome! Did you want to join our discord https://discord.gg/rNxNGQXWsU ? Or we can use github discussions: https://github.com/StateSmith/StateSmith-drawio-plugin/discussions
